=== doo-bluh-vay/invoice-extractor-checker/schema/invoice-schema-1_0_0.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/invoice",
  "definitions": {
    "invoice": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Template name. Must be unique across all templates part of the system.",
          "type": "string"
        },
        "keywords": {
          "description": "A list of all the text that would exist in the pdf. If matches, apply this template.",
          "type": "array",
          "minItems": 1,
          "uniqueItems": true,
          "items": {
            "type": "string"
          }
        },
        "fields": {
          "description": "List of fields to pick and information about where and how to pick a field's content.",
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/field"
          }
        }, 
        "table_lineitems": {
          "description": "Information about where and how to pick table line items.",
          "$ref": "#/definitions/table_lineitem"
        }, 
        "regex_lineitems": {
          "description": "Information about where and how to pick regex based line items.",
          "$ref": "#/definitions/regex_lineitem"
        }, 
        "check": {
          "description": "Checker to check if totals match.",
          "$ref": "#/definitions/check"
        },
        "plugin": {
          "description": "Name of the plugin that needs to be loaded and called for customizations.",
          "type": "string"
        }        
     },
      "required": [
        "name",
        "keywords"
      ],
      "additionalProperties": false
    },
    "field": {
      "description": "Definition on from where and how to pick a field's content",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the field.",
          "type": "string"
        },
        "location": {
          "description": "Identify the location of the field.",
          "type": "string",
          "enum": [
            "right",
            "second-right",
            "bottom",
            "regex",            
            "regex-right",
            "regex-second-right",
            "regex-bottom"
          ]
        },        
        "identifier": {
          "description": "Identifying the field. Can use regex.",
          "type": "string"
        },        
        "ordinal": {
          "description": "Ordinal (first, second ...).",
          "type": "number",
          "minimum":1,
          "maximum":5
        }
      },
      "required": [
        "name",
        "location",
        "identifier"
      ],
      "additionalProperties": false
    },
    "table_lineitem": {
      "description": "Definition on from where and how to pick a table line item's content",
      "type": "object",
      "properties": {
        "horizontal_lines": {
          "description": "Does this have horizontal lines in between rows?",
          "type": "boolean"
        },
        "vertical_lines": {
          "description": "Does this have vertical lines in between columns?",
          "type": "boolean"
        },
        "columns": {
          "description": "Information about the columns.",
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/table_lineitem_column"
          }          
        },        
        "line_end": {
          "description": "Identifying the end of table line items. Can use regex.",
          "type": "string"
        }
      },
      "required": [
        "horizontal_lines",
        "vertical_lines",
        "columns",
        "line_end"
      ],
      "additionalProperties": false
    },
    "table_lineitem_column": {
      "description": "Table Line item column information.",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the column",
          "type": "string"
        },
        "row_start": {
          "description": "Will this column have information to identify that its the start of a row?",
          "type": "boolean"
        },
        "alignment": {
          "description": "Column alignment.",
          "type": "string",
          "enum": [
            "left",
            "right",
            "center"            
          ]
        },
        "can_extend_text_to_neighbour": {
          "description": "Can the text extend till the next column so that it needs a split?",
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "row_start",
        "alignment"
      ],
      "additionalProperties": false
    },    
    "regex_lineitem": {
      "description": "Definition on from where and how to pick a regex line item's content",
      "type": "object",
      "properties": {
        "line_start": {
          "description": "regex used to identify the start of line item. Basically the line item header.",
          "type": "string"
        },
        "line_end": {
          "description": "regex used to identify the end of line items.",
          "type": "string"
        },        
        "lines": {
          "description": "regex used to identify a line item.",
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string"
          }
        }, 
        "columns": {
          "description": "The list of columns identified in a line item.",
          "type": "array",
          "minItems": 1,
          "uniqueItems": true,
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "line_start",
        "line_end",
        "lines",
        "columns"
      ],
      "additionalProperties": false
    }, 
    "check": {
      "description": "Definition on from where and how to pick a regex line item's content",
      "type": "object",
      "properties": {
        "field": {
          "description": "Field whose value needs to be used for checking.",
          "$ref": "#/definitions/check_detail"
        },
        "lineitem": {
          "description": "Line Item column whose value needs to be used for checking.",
          "$ref": "#/definitions/check_detail"
        }        
      },
      "required": [
        "field",
        "lineitem"
      ],
      "additionalProperties": false
    },
    "check_detail": {
      "description": "Checker details",
      "type": "object",
      "properties": {
        "name": {
          "description": "Column name",
          "type": "string"
        },
        "regex": {
          "description": "regex to be used to extract the number",
          "type": "string"
        }
      },
      "required": [
        "name"
      ],
      "additionalProperties": false
    }    
   }
}

=== doo-bluh-vay/invoice-extractor-checker/template/Amazon-Storeji.json
{
    "name":"Amazon-Storeji",
    "keywords":[
        "Storeji Pvt Ltd"
    ],
    "fields":[
        {
            "name":"Invoice Number",
	    "location":"right",
            "identifier":"Invoice Number:"
        },
        {
            "name":"Invoice Date",
            "location":"right",
            "identifier":"Invoice Date:"
        },
        {
            "name":"Total",
            "location":"second-right",
            "identifier":"TOTAL:"
        },
        {
            "name":"AmountInWords",
            "location":"bottom",
            "identifier":"Amount in Words:"
        }
    ],
    "table_lineitems":{
        "horizontal_lines" : true,
        "vertical_lines" : true,
        "columns":[
        {
            "name":"Sl.\nNo",
            "row_start":true,
            "alignment":"center"
        },
        {
            "name":"Description",
            "row_start":true,
            "alignment":"left"
        },
        {
            "name":"Unit\nPrice",
            "row_start":true,
            "alignment":"center"
        },
        {
            "name":"Quantity",
            "row_start":true,
            "alignment":"center"
        },
        {
            "name":"Net\nAmount",
            "row_start":true,
            "alignment":"center"
        },
        {
            "name":"Tax\nRate",
            "row_start":true,
            "alignment":"center"
        },
        {
            "name":"Tax\nType",
            "row_start":true,
            "alignment":"center"
        },
        {
            "name":"Tax\nAmount",
            "row_start":true,
            "alignment":"center"
        },
        {
            "name":"Total\nAmount",
            "row_start":true,
            "alignment":"center"
        }        
        ],
        "line_end":"TOTAL:"    
    },
    "check":{
        "field":
        {
            "name":"Total",
            "regex":"(?P<Total>\\d+(,\\d+)*(\\.\\d+)?)"
        },
        "lineitem":
        {
            "name":"Total\nAmount",
            "regex":"(?P<Total>\\d+(,\\d+)*(\\.\\d+)?)"
        }
    }

}

=== doo-bluh-vay/invoice-extractor-checker/template/FlipKart-WSRetail.json
{
    "name":"Flipkart",
    "keywords":[
        "WS Retail Services Pvt. Ltd"
    ],
    "fields":[
        {
            "name":"Invoice Number",
	    "location":"regex",
            "identifier":"Invoice No :\\s+(.*)"
        },
        {
            "name":"Invoice Date",
            "location":"right",
            "identifier":"Invoice Date:"
        },
        {
            "name":"Total",
            "location":"right",
            "identifier":"Grand Total"
        }
    ],
    "table_lineitems":{
        "horizontal_lines" : false,
        "vertical_lines" : false,
        "columns":[
        {
            "name":"Product",
            "row_start":false,
            "alignment":"left"
        },
        {
            "name":"Title",
            "row_start":false,
            "alignment":"center"
        },
        {
            "name":"Qty",
            "row_start":true,
            "alignment":"right"
        },
        {
            "name":"Price ",
            "row_start":true,
            "alignment":"center"
        },
        {
            "name":"Tax(%)",
            "row_start":false,
            "alignment":"center"
        },
        {
            "name":"Tax ",
            "row_start":true,
            "alignment":"center"
        },
        {
            "name":"Total ",
            "row_start":true,
            "alignment":"center"
        }       
        ],
        "line_end":"Total"    
    },
    "check":{
        "field":
        {
            "name":"Total"
        },
        "lineitem":
        {
            "name":"Total ",
            "regex":"(?P<Total>(-)?\\d+(,\\d+)*(\\.\\d+)?)"
        }
    }

}

=== doo-bluh-vay/invoice-extractor-checker/template/FlipKart-ShreyasRetail.json
{
    "name":"Flipkart",
    "keywords":[
        "Shreyash Retail Private Limited"
    ],
    "fields":[
        {
            "name":"Invoice Number",
	    "location":"right",
            "identifier":"Invoice Number"
        },
        {
            "name":"Invoice Date",
            "location":"right",
            "identifier":"Invoice Date"
        },
        {
            "name":"Total",
            "location":"second-right",
            "identifier":"Summary"
        }
    ],
    "table_lineitems":{
        "horizontal_lines" : false,
        "vertical_lines" : false,
        "columns":[
        {
            "name":"S.\nNo",
            "row_start":true,
            "alignment":"left"
        },
        {
            "name":"Item",
            "row_start":true,
            "alignment":"left"
        },
        {
            "name":"HSN\n(Tax%)",
            "row_start":true,
            "alignment":"left"
        },
        {
            "name":"Qty",
            "row_start":true,
            "alignment":"center"
        },
        {
            "name":"MRP\n(Rs)",
            "row_start":true,
            "alignment":"center"
        },
        {
            "name":"Savings\n(Rs)",
            "row_start":true,
            "alignment":"center"
        },
        {
            "name":"Total\nAmt(Rs)",
            "row_start":true,
            "alignment":"center"
        }       
        ],
        "line_end":"Summary"    
    },
    "check":{
        "field":
        {
            "name":"Total"
        },
        "lineitem":
        {
            "name":"Total\nAmt(Rs)"
        }
    }

}
